### ISSUE TITLE
This issue needs to be solved quickly!

### ISSUE THREAD

**Issue by mktcode** [mktcode/mktcode#3]
The title of the README needs to be changed from "About Me" to "About Myself" asap!

Can anyone sponsor it with ETH through https://ethbooster.github.io please? That would be amazing!

**Comment by bonustrack** [comment]
Hey! I just deposited 0.1 ETH for this issue. Whoever solves it via a merged pull request. Can withdraw the bounty [here](https://github.com/ethbooster/oracle/issues/new?template=withdraw.md&title=Withdraw)

As the maintainer, comment "/release-eth @user" to release the bounty manually.

You can see the transaction [here](https://kovan.etherscan.io/tx/0xd72dffae06fefda8d6e6dc826b14ee3844bb4acd371ddaa7ef689fa62780e81b).

**Comment by mktcode** [comment]
The deposits from this issue have been withdrawn. Tx: 0x355f2bebb865cff241dc20ca559ca6845f78e4052d14c100215002578510112e

**Comment by mktcode** [comment]
asdasd
